-- MySQL Script generated by MySQL Workbench
-- Mon Jul  7 17:21:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.``
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`` (
  `batch_code` INT NOT NULL AUTO_INCREMENT,
  `Start_date` DATE NULL,
  `End_date` DATE NULL,
  `Course_id` INT NULL,
  PRIMARY KEY (`batch_code`))
ENGINE = InnoDB
KEY_BLOCK_SIZE = 1;


-- -----------------------------------------------------
-- Table `mydb`.`COURSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COURSE` (
  `Course id` INT NOT NULL,
  `Course_name` VARCHAR(45) NULL,
  PRIMARY KEY (`Course id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BATCHES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BATCHES` (
  `Batch_code` INT NOT NULL,
  `Start_date` DATE NULL,
  `End_date` DATE NULL,
  `Course_id` INT NULL,
  PRIMARY KEY (`Batch_code`),
  INDEX `course_idx` (`Course_id` ASC) VISIBLE,
  CONSTRAINT `course`
    FOREIGN KEY (`Course_id`)
    REFERENCES `mydb`.`COURSE` (`Course id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Topics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Topics` (
  `Topic_No` INT NOT NULL,
  `Topic_name` VARCHAR(45) NULL,
  `Course_id` INT NULL,
  PRIMARY KEY (`Topic_No`),
  INDEX `Course_idx` (`Course_id` ASC) VISIBLE,
  CONSTRAINT `Course`
    FOREIGN KEY (`Course_id`)
    REFERENCES `mydb`.`COURSE` (`Course id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CANDIDATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CANDIDATE` (
  `Cndt_ID` INT NOT NULL,
  `Cndt_name` VARCHAR(45) NULL,
  `Cndt_email` VARCHAR(45) NULL,
  `Cndt_phone` BIGINT(10) NULL,
  `Cndt_Status` VARCHAR(45) NULL,
  PRIMARY KEY (`Cndt_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TRAINERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TRAINERS` (
  `Trainer_ID` INT NOT NULL,
  `Trainer_name` VARCHAR(45) NULL,
  `Trainer_email` VARCHAR(45) NULL,
  PRIMARY KEY (`Trainer_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ASSIGNMENTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ASSIGNMENTS` (
  `Number` INT NOT NULL,
  `Title` VARCHAR(45) NULL,
  `Description` VARCHAR(45) NULL,
  `Due_date` DATE NULL,
  `Batch` INT NULL,
  PRIMARY KEY (`Number`),
  INDEX `Batch_idx` (`Batch` ASC) VISIBLE,
  CONSTRAINT `Batch`
    FOREIGN KEY (`Batch`)
    REFERENCES `mydb`.`BATCHES` (`Batch_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SUBMISSIONS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SUBMISSIONS` (
  `SID` INT NOT NULL,
  `Cndt_id` INT NULL,
  `Assignment_number` INT NULL,
  `Score` INT NULL,
  PRIMARY KEY (`SID`),
  INDEX `candidate_idx` (`Cndt_id` ASC) VISIBLE,
  INDEX `assignment_idx` (`Assignment_number` ASC) VISIBLE,
  CONSTRAINT `candidate`
    FOREIGN KEY (`Cndt_id`)
    REFERENCES `mydb`.`CANDIDATE` (`Cndt_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `assignment`
    FOREIGN KEY (`Assignment_number`)
    REFERENCES `mydb`.`ASSIGNMENTS` (`Number`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Batch_trainers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Batch_trainers` (
  `Batch_code` INT NOT NULL,
  `Trainer_id` INT NOT NULL,
  PRIMARY KEY (`Batch_code`, `Trainer_id`),
  INDEX `Trainer_idx` (`Trainer_id` ASC) VISIBLE,
  CONSTRAINT `Trainer`
    FOREIGN KEY (`Trainer_id`)
    REFERENCES `mydb`.`TRAINERS` (`Trainer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Batch`
    FOREIGN KEY (`Batch_code`)
    REFERENCES `mydb`.`BATCHES` (`Batch_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Batch_candidates`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Batch_candidates` (
  `Candidate_id` INT NOT NULL,
  `Batch_code` INT NOT NULL,
  PRIMARY KEY (`Candidate_id`, `Batch_code`),
  INDEX `candidate_idx` (`Candidate_id` ASC) VISIBLE,
  CONSTRAINT `batch`
    FOREIGN KEY (`Batch_code`)
    REFERENCES `mydb`.`BATCHES` (`Batch_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `candidate`
    FOREIGN KEY (`Candidate_id`)
    REFERENCES `mydb`.`CANDIDATE` (`Cndt_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADMIN`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ADMIN` (
  `Admin_id` INT NOT NULL,
  `Admin_name` VARCHAR(45) NULL,
  PRIMARY KEY (`Admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USERS` (
  `Login id` INT NOT NULL,
  `Password` VARCHAR(45) NULL,
  `User-type` VARCHAR(45) NULL,
  `Reference_id` INT NULL,
  PRIMARY KEY (`Login id`),
  INDEX `user type_idx` (`Reference_id` ASC) VISIBLE,
  CONSTRAINT `user type`
    FOREIGN KEY (`Reference_id`)
    REFERENCES `mydb`.`CANDIDATE` (`Cndt_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `usertype`
    FOREIGN KEY (`Reference_id`) 
    REFERENCES `mydb`.`TRAINERS` (`Trainer_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userr type`
    FOREIGN KEY (`Reference_id`)
    REFERENCES `mydb`.`ADMIN` (`Admin_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`table1` (
)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
